### ISSUE TITLE
Quand est-ce que l'on se voit ?

### ISSUE THREAD

**Issue by alepee** [jeromeludmann/minesweeper-kata#1]
Merci d'avoir pris le temps de répondre à mes commentaires 😃 
As-tu des dispos pour que l'on se rencontre ?

**Comment by jeromeludmann** [comment]
Merci à toi d'avoir fait cette relecture.

Jeudi en fin de matinée à partir de 11h15-11h30, ou jeudi en début d'après midi ?

**Comment by alepee** [comment]
Jeudi en fin de matinée ça me va. Au plus tôt à 11h15 ou tu peux un peu avant ? L'idéal pour moi serait 10h30 😅

**Comment by jeromeludmann** [comment]
J'ai un entretien à 10h00 dans le 2e, ça va être limite. Je ne pense pas que cet entretien dure plus d'une heure par contre.

**Comment by alepee** [comment]
Ok, je note jeudi 11h15 histoire que l'on puisse se caler et booker une salle et on fait au mieux

Nous sommes au 27 rue de Mogador, depuis la rue il y a un bouton jour, puis tu peux demander simplement aux personnes que tu croiseras dans la cour que tu as rendez-vous avec moi.

**Comment by jeromeludmann** [comment]
Ça marche pour 11h15 👍

**Comment by jeromeludmann** [comment]
Si jamais 10h30 t'arrange davantage que 11h15, c'est OK pour moi. 

La personne que je devais voir en début de matinée vient d'annuler le rendez-vous.

**Comment by alepee** [comment]
J'ai un micro truc à régler à 10h30, mais 10h45 ce serai parfait 👌

**Comment by jeromeludmann** [comment]
OK merci ! 10h45 alors 👍
